import { Hospital, Meal, Offer, MealCategory } from './types';
import { LOCAL_IMAGES } from './utils/localImages';

export const HOSPITALS: Hospital[] = [
  {
    id: 'bgh',
    name: 'Government Hospital',
    image: LOCAL_IMAGES.hospitalMangalore,
    location: 'Bunder Road, Bhatkal',
    rating: 4.2,
  },
  {
    id: 'welfare',
    name: 'Welfare Hospital',
    image: LOCAL_IMAGES.hospitalMangalore,
    location: 'Sowda Cargo Street, Bhatkal',
    rating: 4.7,
  },
  {
    id: 'shamsnoor',
    name: 'Shams Noor Hospital',
    image: LOCAL_IMAGES.hospitalMangalore,
    location: 'Shamsuddin Circle, Bhatkal',
    rating: 4.5,
  },
  {
    id: 'asiya',
    name: 'Asiya Hospital',
    image: LOCAL_IMAGES.hospitalMangalore,
    location: 'National Highway 66, Bhatkal',
    rating: 4.4,
  },
  {
    id: 'lifecare',
    name: 'Lifecare Hospital',
    image: LOCAL_IMAGES.hospitalMangalore,
    location: 'Main Road, Bhatkal',
    rating: 4.6,
  },
];

export const OFFERS: Offer[] = [
  {
    id: 'heal100',
    code: 'HEAL100',
    title: 'First Order Special',
    description: 'Get ₹100 flat discount on your first healthy order.',
    discountPercentage: 20, // custom logic or flat rate, we can support percent
    minOrderValue: 250,
  },
  {
    id: 'recover',
    code: 'RECOVER50',
    title: 'Get Well Soon Discount',
    description: 'Enjoy 15% off up to ₹150 for all nutritious meals.',
    discountPercentage: 15,
    minOrderValue: 200,
  },
  {
    id: 'nutri',
    code: 'NUTRIFIT',
    title: 'High Protein Discount',
    description: 'Flat 10% off for custom high-protein lunches.',
    discountPercentage: 10,
    minOrderValue: 150,
  },
];

export const SAMPLE_REVIEWS = [
  {
    id: 'r1',
    userName: 'Zainab Fatima',
    rating: 5,
    comment: 'Very light on the stomach, zero oil feel. The Upma was perfectly cooked and hot when delivered to the 3rd floor ward.',
    date: 'Today',
  },
  {
    id: 'r2',
    userName: 'Mohammed Rayan',
    rating: 5,
    comment: 'The Veg Lunch plate is incredible! It has Dal, Rice, Salad, Curd and even a small cup of hot vegetable soup. Recovering much better now!',
    date: 'Yesterday',
  },
  {
    id: 'r3',
    userName: 'Dr. Aditya Naik',
    rating: 4.5,
    comment: 'Highly recommended for diabetic and post-surgery patients. Very nutritious, low sodium, and clean packaging.',
    date: '2 days ago',
  },
];

export const MEALS: Meal[] = [
  // ==========================================
  // BREAKFAST (Breakfast Thali Options - Price ₹100)
  // ==========================================
  {
    id: 'bf-doc-veg',
    name: "Steamed Vegetable Idli with Thin Sambhar & Fresh Curd Thali",
    image: LOCAL_IMAGES.idliThali,
    price: 100,
    rating: 4.9,
    calories: 220,
    protein: 9,
    category: 'Breakfast',
    isVeg: true,
    isPopular: true,
    isHealthySpecial: true,
    isDoctorRecommended: true,
    clinicalTags: ["Post-Surgery Recovery", "Diabetes Management", "Hypertension & Cardiac Care"],
    clinicalDiagnosisSuggestion: "Prescribed to soothe digestion, regulate high blood sugar, or during cardiac bedrest. Steam-fermented, zero oil, and served with probiotic fresh set curd.",
    description: 'Complete Breakfast Thali—Fluffy steamed idlis packed with carrots and green beans, served with thin sambhar and a bowl of fresh low-fat set curd.',
    ingredients: ['Steamed Rice Batter', 'Carrots', 'Beans', 'Thin Sambar', 'Fresh Low-Fat Curd Bowl'],
    nutrition: { calories: 220, protein: 9, carbs: 38, fat: 2, prepTimeMinutes: 12 },
    reviews: [SAMPLE_REVIEWS[0]],
  },
  {
    id: 'bf-doc-nonveg',
    name: "Shoupa Pana (Dill Leaves Crepe) & Fresh Curd Thali",
    image: LOCAL_IMAGES.crepeThali,
    price: 100,
    rating: 4.8,
    calories: 230,
    protein: 8,
    category: 'Breakfast',
    isVeg: true,
    isHealthySpecial: true,
    isDoctorRecommended: true,
    clinicalTags: ["Maternity & Lactation", "Digestive Healing", "Mild Acidity Care"],
    clinicalDiagnosisSuggestion: "Nourishing traditional herb-infused steamed cakes. Dill leaves promote maternal lactation and soothe stomach walls.",
    description: 'Complete Breakfast Thali—Traditional herb-infused steamed rice crepe flavored with fresh dill leaves, coconut chutney, and a bowl of soothing low-fat set curd.',
    ingredients: ['Rice Flour', 'Dill Leaves', 'Light Jaggery', 'Coconut Chutney', 'Fresh Low-Fat Curd Bowl'],
    nutrition: { calories: 230, protein: 8, carbs: 40, fat: 3, prepTimeMinutes: 10 },
    reviews: [SAMPLE_REVIEWS[2]],
  },
  {
    id: 'bf-norm-veg',
    name: "Oats Vegetable Upma with Fresh Curd Thali",
    image: LOCAL_IMAGES.upmaThali,
    price: 100,
    rating: 4.6,
    calories: 210,
    protein: 8,
    category: 'Breakfast',
    isVeg: true,
    isDoctorRecommended: true,
    clinicalTags: ["High Fiber", "Diabetes Management", "Heart Healthy"],
    clinicalDiagnosisSuggestion: "Low-glycemic breakfast. Oats beta-glucans help regulate cholesterol and maintain blood glucose levels.",
    description: 'Complete Breakfast Thali—High-fiber dry-roasted rolled oats cooked with carrots and green peas, served with fresh coconut chutney and low-fat set curd.',
    ingredients: ['Rolled Oats', 'Green Peas', 'Carrots', 'Coconut Chutney', 'Fresh Low-Fat Curd Bowl'],
    nutrition: { calories: 210, protein: 8, carbs: 32, fat: 3, prepTimeMinutes: 10 },
    reviews: [],
  },
  {
    id: 'bf-norm-nonveg',
    name: "Golden Dosa with Vegetable Kootu & Fresh Curd Thali",
    image: LOCAL_IMAGES.dosaThali,
    price: 100,
    rating: 4.7,
    calories: 250,
    protein: 7,
    category: 'Breakfast',
    isVeg: true,
    isDoctorRecommended: true,
    clinicalTags: ["Digestive Healing", "Mild Acidity Care", "Low Sodium"],
    clinicalDiagnosisSuggestion: "Thin oil-free fermented rice-and-lentil crepe served with a mild, water-based vegetable Kootu and probiotic fresh curd bowl.",
    description: 'Complete Breakfast Thali—Golden oil-free fermented rice crepe paired with soothing vegetable stew and a bowl of fresh set curd.',
    ingredients: ['Fermented Rice Crepe', 'Ash Gourd Kootu', 'Moong Dal', 'Fresh Low-Fat Curd Bowl'],
    nutrition: { calories: 250, protein: 7, carbs: 42, fat: 4, prepTimeMinutes: 12 },
    reviews: [],
  },
  {
    id: 'bf-egg-banana-yogurt',
    name: "Boiled Egg, Fresh Banana & Low-Fat Yogurt Thali",
    image: LOCAL_IMAGES.eggBananaYogurtThali,
    price: 100,
    rating: 4.9,
    calories: 280,
    protein: 16,
    category: 'Breakfast',
    isVeg: false,
    isPopular: true,
    isHealthySpecial: true,
    isDoctorRecommended: true,
    clinicalTags: ["High Protein Recovery", "Gut Health & Probiotics", "Post-Op Strength"],
    clinicalDiagnosisSuggestion: "Complete nutrient-rich breakfast platter combining 2 organic boiled egg whites/halves, a fresh potassium-rich banana, and probiotic low-fat set curd for rapid intestinal recovery and wound healing.",
    description: 'Complete Breakfast Thali—2 soft organic boiled eggs, fresh ripe robusta banana, and a 150g smooth low-fat set curd bowl.',
    ingredients: ['2 Organic Boiled Eggs', 'Fresh Robusta Banana', 'Low-Fat Probiotic Yogurt Bowl', 'Pinch of Black Pepper'],
    nutrition: { calories: 280, protein: 16, carbs: 32, fat: 4.5, prepTimeMinutes: 8 },
    reviews: [SAMPLE_REVIEWS[1]],
  },

  // ==========================================
  // LUNCH (Lunch Thali Options - Price ₹210)
  // ==========================================
  {
    id: 'lh-doc-veg',
    name: "The Healing Veg Recovery Thali (Curd Included)",
    image: LOCAL_IMAGES.vegLunchThali,
    price: 210,
    rating: 4.9,
    calories: 420,
    protein: 14,
    category: 'Lunch',
    isVeg: true,
    isPopular: true,
    isHealthySpecial: true,
    isDoctorRecommended: true,
    clinicalTags: ["Clinical Post-Surgery", "Cardiac & Renal Care", "Hypertension Protocol"],
    clinicalDiagnosisSuggestion: "Formulated for patients on salt restrictions. Includes therapeutic gourds, yellow moong dal, and a fresh low-fat set curd bowl.",
    description: 'Complete Lunch Thali—Unpolished red rice, watery therapeutic gourd stew (Kootu), low-oil cabbage Poriyal, fresh cucumber salad, and a bowl of set curd.',
    ingredients: ['Unpolished Red Rice', 'Ash Gourd Kootu', 'Cabbage Poriyal', 'Fresh Low-Fat Curd Bowl', 'Cucumber Salad'],
    nutrition: { calories: 420, protein: 14, carbs: 68, fat: 5, prepTimeMinutes: 15 },
    reviews: [SAMPLE_REVIEWS[0], SAMPLE_REVIEWS[1]],
  },
  {
    id: 'lh-doc-nonveg',
    name: "The High-Protein Non-Veg Coastal Thali (Boiled Egg & Curd Included)",
    image: LOCAL_IMAGES.nonvegLunchThali,
    price: 210,
    rating: 4.8,
    calories: 580,
    protein: 38,
    category: 'Lunch',
    isVeg: false,
    isHealthySpecial: true,
    isDoctorRecommended: true,
    clinicalTags: ["High Energy For Caregivers", "Tissue Rebuilding", "Protein Recovery"],
    clinicalDiagnosisSuggestion: "High-protein meal for caregivers or recovering patients needing tissue building. Rich in lean amino acids.",
    description: 'Complete Lunch Thali—Unpolished red rice, lean chicken/coastal fish curry, soft boiled egg, fresh set curd, and ridge gourd stir-fry.',
    ingredients: ['Unpolished Red Rice', 'Coastal Fish / Chicken Curry', 'Boiled Egg', 'Fresh Low-Fat Curd Bowl', 'Ridge Gourd Upkari'],
    nutrition: { calories: 580, protein: 38, carbs: 72, fat: 12, prepTimeMinutes: 20 },
    reviews: [SAMPLE_REVIEWS[2]],
  },

  // ==========================================
  // SOUP (Fresh, Hot Recovery Soups)
  // ==========================================
  {
    id: 'sp-tomato',
    name: "Hot Clinical Tomato & Carrot Soup",
    image: LOCAL_IMAGES.soupTomato,
    price: 39,
    rating: 4.7,
    calories: 110,
    protein: 3,
    category: 'Soup',
    isVeg: true,
    isPopular: true,
    description: 'A comforting blend of hand-picked tomatoes and sweet carrots simmered with wild garden herbs and a touch of roasted cumin. Low sodium and highly digestible.',
    ingredients: ['Tomatoes', 'Carrots', 'Garden Herbs', 'Cumin Seeds', 'Black Pepper'],
    nutrition: { calories: 110, protein: 3, carbs: 22, fat: 1, prepTimeMinutes: 10 },
    reviews: [],
  },
  {
    id: 'sp-chicken',
    name: "Medicinal Chicken Bone Broth",
    image: LOCAL_IMAGES.soupBroth,
    price: 42,
    rating: 4.9,
    calories: 140,
    protein: 12,
    category: 'Soup',
    isVeg: false,
    isHealthySpecial: true,
    description: 'Slow-simmered organic chicken bone marrow broth enriched with immunity-boosting turmeric, crushed ginger, and cracked black pepper. Excellent for recovery.',
    ingredients: ['Chicken Bone Stock', 'Ginger', 'Turmeric', 'Black Pepper', 'Fresh Parsley'],
    nutrition: { calories: 140, protein: 12, carbs: 4, fat: 3.5, prepTimeMinutes: 15 },
    reviews: [],
  },
  {
    id: 'sp-lentil',
    name: "Immunity Lentil Garlic Soup",
    image: LOCAL_IMAGES.soupLentil,
    price: 35,
    rating: 4.6,
    calories: 130,
    protein: 8,
    category: 'Soup',
    isVeg: true,
    description: 'A nutritious clear split yellow lentil soup flavored with roasted garlic cloves, fresh spinach shreds, and lemon zest. Rich in natural iron.',
    ingredients: ['Yellow Moong Dal', 'Garlic', 'Baby Spinach', 'Lemon Juice', 'Turmeric'],
    nutrition: { calories: 130, protein: 8, carbs: 20, fat: 2, prepTimeMinutes: 12 },
    reviews: [],
  },
  {
    id: 'sp-mushroom',
    name: "Creamy Mushroom & Herb Potage",
    image: LOCAL_IMAGES.soupMushroom,
    price: 39,
    rating: 4.5,
    calories: 125,
    protein: 4,
    category: 'Soup',
    isVeg: true,
    description: 'Finely pureed fresh button mushrooms simmered with light almond milk, thyme, and cracked green peppercorns. Dairy-free and extremely light.',
    ingredients: ['Button Mushrooms', 'Almond Milk', 'Fresh Thyme', 'Green Peppercorn'],
    nutrition: { calories: 125, protein: 4, carbs: 16, fat: 3, prepTimeMinutes: 12 },
    reviews: [],
  },

  // ==========================================
  // JUICE (Exactly 6 Fresh Juice Types)
  // ==========================================
  {
    id: 'jc-orange',
    name: "Cold-Pressed Sweet Orange Juice",
    image: LOCAL_IMAGES.juiceOrange,
    price: 90,
    rating: 4.8,
    calories: 95,
    protein: 1.5,
    category: 'Juice',
    isVeg: true,
    isPopular: true,
    description: '100% natural, freshly squeezed Nagpur oranges with no added sugar, artificial sweeteners, or preservatives. Loaded with Vitamin C.',
    ingredients: ['Nagpur Oranges', 'Mint Leaf'],
    nutrition: { calories: 95, protein: 1.5, carbs: 22, fat: 0.1, prepTimeMinutes: 5 },
    reviews: [],
  },
  {
    id: 'jc-beetroot',
    name: "Detox Beetroot & Pomegranate Blend",
    image: LOCAL_IMAGES.juiceBeetroot,
    price: 90,
    rating: 4.9,
    calories: 110,
    protein: 2,
    category: 'Juice',
    isVeg: true,
    description: 'A vibrant, deep red nectar of fresh organic beetroot, red apples, and sweet pomegranate seeds. Restores hemoglobin levels quickly.',
    ingredients: ['Beetroot', 'Pomegranate Seeds', 'Red Apple'],
    nutrition: { calories: 110, protein: 2, carbs: 26, fat: 0.2, prepTimeMinutes: 6 },
    reviews: [],
  },
  {
    id: 'jc-ginger',
    name: "Anti-Inflammatory Ginger & Turmeric Tonic",
    image: LOCAL_IMAGES.juiceGinger,
    price: 90,
    rating: 4.7,
    calories: 70,
    protein: 1,
    category: 'Juice',
    isVeg: true,
    description: 'A cold-pressed wellness elixir of carrots, green apples, fresh ginger root, and organic turmeric. Powerfully fights cellular inflammation.',
    ingredients: ['Carrot', 'Green Apple', 'Fresh Ginger', 'Turmeric Root'],
    nutrition: { calories: 70, protein: 1, carbs: 16, fat: 0.3, prepTimeMinutes: 5 },
    reviews: [],
  },
  {
    id: 'jc-watermelon',
    name: "Fresh Watermelon & Mint Cooler",
    image: LOCAL_IMAGES.juiceWatermelon,
    price: 90,
    rating: 4.6,
    calories: 80,
    protein: 1,
    category: 'Juice',
    isVeg: true,
    description: 'Hydrating watermelon nectar blended with freshly plucked garden mint leaves. Extremely refreshing for hospital ward summer days.',
    ingredients: ['Watermelon Chunks', 'Garden Mint'],
    nutrition: { calories: 80, protein: 1, carbs: 18, fat: 0.1, prepTimeMinutes: 5 },
    reviews: [],
  },
  {
    id: 'jc-coconut',
    name: "Pure Clinical Coconut Water",
    image: LOCAL_IMAGES.juiceCoconut,
    price: 60,
    rating: 4.9,
    calories: 45,
    protein: 0.5,
    category: 'Juice',
    isVeg: true,
    isPopular: true,
    description: 'Freshly tapped tender coastal coconut water packed with natural potassium, magnesium, and hydration electrolytes.',
    ingredients: ['Tender Coconut Water'],
    nutrition: { calories: 45, protein: 0.5, carbs: 10, fat: 0, prepTimeMinutes: 4 },
    reviews: [],
  },
  {
    id: 'jc-lime',
    name: "Digestive Sweet Lime Juice",
    image: LOCAL_IMAGES.juiceLime,
    price: 90,
    rating: 4.7,
    calories: 85,
    protein: 1,
    category: 'Juice',
    isVeg: true,
    description: 'Freshly pressed sweet lime (Mosambi) juice with a pinch of digestive black salt. Stimulates appetite and settles nausea.',
    ingredients: ['Sweet Lime', 'Black Salt'],
    nutrition: { calories: 85, protein: 1, carbs: 20, fat: 0.1, prepTimeMinutes: 5 },
    reviews: [],
  },

  // ==========================================
  // SNACKS (Healthy Recovery Snacks)
  // ==========================================
  {
    id: 'sn-fruit-bowl',
    name: 'Immunity Fruit Bowl',
    image: LOCAL_IMAGES.snackFruitBowl,
    price: 90,
    rating: 4.7,
    calories: 140,
    protein: 2,
    category: 'Snacks',
    isVeg: true,
    isPopular: false,
    isHealthySpecial: true,
    description: 'A vibrant selection of freshly sliced seasonal fruits packed with Vitamin C and fiber to boost recovery. Includes sweet papaya, pomegranate, crisp apple, banana, and a splash of lemon juice.',
    ingredients: ['Papaya', 'Apple', 'Pomegranate Seeds', 'Banana', 'Kiwi', 'Fresh Lemon'],
    nutrition: { calories: 140, protein: 2, carbs: 33, fat: 0.5, prepTimeMinutes: 8 },
    reviews: [],
  },
  {
    id: 'sn-sprouts',
    name: 'Sprouts & Paneer Salad',
    image: LOCAL_IMAGES.snackSprouts,
    price: 85,
    rating: 4.5,
    calories: 190,
    protein: 14,
    category: 'Snacks',
    isVeg: true,
    description: 'A high-protein mid-day snack of steamed green gram (moong) sprouts, diced fresh cottage cheese (paneer), cucumber, and tomatoes, tossed with fresh coriander and lemon dressing.',
    ingredients: ['Moong Sprouts', 'Fresh Paneer', 'Cucumber', 'Tomatoes', 'Coriander', 'Lemon Juice', 'Black Pepper'],
    nutrition: { calories: 190, protein: 14, carbs: 18, fat: 6, prepTimeMinutes: 10 },
    reviews: [SAMPLE_REVIEWS[2]],
  },
  {
    id: 'sn-makhana',
    name: 'Roasted Low-Salt Organic Makhana',
    image: LOCAL_IMAGES.snackMakhana,
    price: 75,
    rating: 4.8,
    calories: 120,
    protein: 3.5,
    category: 'Snacks',
    isVeg: true,
    description: 'Crispy dry-roasted water lily seeds tossed with organic turmeric and a tiny pinch of rock salt. Extremely rich in calcium and low in sodium.',
    ingredients: ['Water Lily Seeds', 'Turmeric', 'Rock Salt', 'Olive Oil Touch'],
    nutrition: { calories: 120, protein: 3.5, carbs: 24, fat: 1.5, prepTimeMinutes: 6 },
    reviews: [],
  },

  // ==========================================
  // GROCERY / ESSENTIALS (Exactly 50 items)
  // ==========================================
  // Caregiver Survival Packs (3 bundled items)
  {
    id: 'gr-overnight',
    name: 'The Overnight Survival Kit',
    image: LOCAL_IMAGES.groceryKit,
    price: 299,
    rating: 4.9,
    calories: 140,
    protein: 2.5,
    category: 'Grocery',
    isVeg: true,
    description: 'The Overnight Kit: A 1L secure mineral water bottle, a pack of pH-balanced sanitizing wet wipes, a 1.5m long mobile charging cable, and a light nutritious digestive snack.',
    ingredients: ['1L Water Bottle', 'Hygienic Wet Wipes (30s)', '1.5m Charging Cable', 'High-Fiber Digestive Biscuits'],
    nutrition: { calories: 140, protein: 2.5, carbs: 22, fat: 5, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-comfort',
    name: 'The Patient Comfort Pack',
    image: LOCAL_IMAGES.groceryKit,
    price: 399,
    rating: 4.8,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Designed to block out ICU machine alerts, dim harsh fluorescent lights, and support peaceful rest. Includes a contoured blackout sleep eye mask, sound-dampening silicone earplugs, an inflatable cervical neck pillow, and a pocket notebook & pen.',
    ingredients: ['Blackout Sleep Mask', 'Silicone Earplugs', 'Inflatable Neck Pillow', 'Pocket Notebook', 'Ballpoint Pen'],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-hygiene',
    name: 'The Hygiene & Protection Bundle',
    image: LOCAL_IMAGES.groceryToiletries,
    price: 199,
    rating: 4.9,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Complete bedside sanitization and personal hygiene shield. Includes a Dettol Hand Sanitizer (50ml), a pack of 10 surgical 3-ply masks, a Dove moisturizing soap bar, and a pack of double-ply facial tissues.',
    ingredients: ['Hand Sanitizer (50ml)', '3-Ply Surgical Masks (10s)', 'Dove Soap Bar', 'Soft Facial Tissues (100 Pcs)'],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  // Toiletries & Hygiene (15 items)
  {
    id: 'gr-sanitizer',
    name: 'Dettol Hand Sanitizer (50ml)',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=400',
    price: 60,
    rating: 4.9,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Alcohol-based instant hand sanitizer, kills 99.9% germs. Essential for clean bedside bedside recovery and caregiver safety.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-wipes',
    name: 'Hygienic Wet Wipes (30 Pcs)',
    image: 'https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&q=80&w=400',
    price: 90,
    rating: 4.8,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Extra soft, pH-balanced sanitizing wet wipes for facial, hand, and bedside surface sterilization.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-toothbrush',
    name: 'Oral-B Soft Bristle Toothbrush',
    image: 'https://images.unsplash.com/photo-1559591937-e4b2d0b42749?auto=format&fit=crop&q=80&w=400',
    price: 40,
    rating: 4.6,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Ultra-soft bedside toothbrush, prevents bleeding gums and maintains optimal oral clinical hygiene.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-paste',
    name: 'Colgate Total Protection (50g)',
    image: 'https://images.unsplash.com/photo-1559592481-7448d3937-e4b2d0b42749?auto=format&fit=crop&q=80&w=400',
    price: 55,
    rating: 4.7,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Active protection toothpaste. Perfect travel size for multi-day clinical admissions.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-soap',
    name: 'Dove Gentle Moisture Soap',
    image: 'https://images.unsplash.com/photo-1607006342411-1a90c9b0e27f?auto=format&fit=crop&q=80&w=400',
    price: 65,
    rating: 4.9,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Hypoallergenic nourishing soap bars, ideal for hospital shower water.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-handwash',
    name: 'Savlon Herbal Liquid Handwash (200ml)',
    image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&q=80&w=400',
    price: 85,
    rating: 4.8,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Antiseptic handwash, keeps bystanders and patient hands completely disinfected before eating.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-tissues',
    name: 'Bedside Soft Facial Tissues (100 Pcs)',
    image: 'https://images.unsplash.com/photo-1607619056574-7b8f30413b58?auto=format&fit=crop&q=80&w=400',
    price: 75,
    rating: 4.7,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Ultra-absorbent double ply bedside facial tissue paper.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-diapers',
    name: 'Friends Adult Diapers (Medium - 10s)',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=400',
    price: 450,
    rating: 4.9,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Leak-proof anti-bacterial overnight absorbent diapers for bedridden post-operation recovery.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-pads',
    name: 'Whisper Ultra Sanitary Pads (8 Pcs)',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=400',
    price: 130,
    rating: 4.8,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Extra-long soft sanitary napkins for hospital bedside hygiene.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-bedsheets',
    name: 'Sterile Disposable Bed Sheets (Set of 2)',
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=400',
    price: 190,
    rating: 4.8,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Non-woven anti-allergic disposable sheets, pre-sanitized for ultimate bedding hygiene.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-comb',
    name: 'Pocket Hair Comb',
    image: 'https://images.unsplash.com/photo-1590156221122-c241e47a2841?auto=format&fit=crop&q=80&w=400',
    price: 20,
    rating: 4.4,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Anti-static gentle personal hair grooming comb.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-hairoil',
    name: 'Parachute Pure Coconut Hair Oil (100ml)',
    image: 'https://images.unsplash.com/photo-1608248597481-496100c80836?auto=format&fit=crop&q=80&w=400',
    price: 45,
    rating: 4.6,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: '100% pure edible coconut oil to soothe skin dryness and maintain scalp care.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-lipbalm',
    name: 'Vaseline Lip Therapy Original',
    image: 'https://images.unsplash.com/photo-1608248597481-496100c80836?auto=format&fit=crop&q=80&w=400',
    price: 50,
    rating: 4.7,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Instant bedside dry-lip hydration relief. Recommended for air-conditioned wards.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-shaving',
    name: 'Gillette Shaving Disposable Razor & Foam',
    image: 'https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&q=80&w=400',
    price: 120,
    rating: 4.6,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Quick single-use hygiene shaving kit containing razor and a travel-size foam.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-mouthwash',
    name: 'Listerine Cool Mint Mouthwash (100ml)',
    image: 'https://images.unsplash.com/photo-1559592481-7448d3937-e4b2d0b42749?auto=format&fit=crop&q=80&w=400',
    price: 95,
    rating: 4.7,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Antibacterial mouthwash for overnight freshness and complete oral hygiene.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },

  // Comfort & Convenience (15 items)
  {
    id: 'gr-slippers',
    name: 'Hospital Anti-Slip Soft Slippers',
    image: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&q=80&w=400',
    price: 150,
    rating: 4.7,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Perfect for walking safely inside clinical wards and sterile tiled bathrooms.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-cablec',
    name: 'Premium USB Type-C Charging Cable (1.5m)',
    image: 'https://images.unsplash.com/photo-1589634749000-1e7243405b12?auto=format&fit=crop&q=80&w=400',
    price: 199,
    rating: 4.8,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Extra-long copper core charging cable. Easily reaches the hospital bedside from distant plugs.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-cableiphone',
    name: 'iPhone Lightning Charging Cable (1.5m)',
    image: 'https://images.unsplash.com/photo-1541667590925-440534c0562e?auto=format&fit=crop&q=80&w=400',
    price: 249,
    rating: 4.7,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Apple-compatible data and high speed charging cable for bedside use.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-cablemicro',
    name: 'Micro-USB High Speed Charging Cable (1.5m)',
    image: 'https://images.unsplash.com/photo-1589634749000-1e7243405b12?auto=format&fit=crop&q=80&w=400',
    price: 149,
    rating: 4.5,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Durable micro-usb fast charging cable to keep accessories and older smartphones charged.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-eyemask',
    name: 'Contoured Sleeping Eye Mask',
    image: 'https://images.unsplash.com/photo-1620121692029-d088224ddc74?auto=format&fit=crop&q=80&w=400',
    price: 99,
    rating: 4.8,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Blackout comfort eye mask to sleep soundly even when ward clinical monitoring lights are on.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-earplugs',
    name: 'Silicone Sound-Dampening Earplugs',
    image: 'https://images.unsplash.com/photo-1620121692029-d088224ddc74?auto=format&fit=crop&q=80&w=400',
    price: 60,
    rating: 4.6,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Reusable hygienic silicone earplugs to block ICU noise, machine beeps, and snoring.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-pillow',
    name: 'Inflatable Orthopedic Cervical Pillow',
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=400',
    price: 299,
    rating: 4.7,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Ergonomic neck support pillow, excellent for bystander chairs and long stays.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-masks',
    name: '3-Ply Surgical Face Masks (Pack of 10)',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=400',
    price: 80,
    rating: 4.9,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Medical grade 3-layer protective face masks with secure elastic ear loops.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-gloves',
    name: 'Sterile Latex Examination Gloves (Pack of 10)',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=400',
    price: 120,
    rating: 4.8,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Powder-free clean latex gloves for sanitation and patient touch care.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-hotbag',
    name: 'Rubber Leak-proof Hot Water Bag',
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&q=80&w=400',
    price: 250,
    rating: 4.7,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Provides deep heat fermentation therapy to relieve joint/muscle pain and cramps.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-thermometer',
    name: 'Accu-Check Digital Body Thermometer',
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&q=80&w=400',
    price: 220,
    rating: 4.8,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Oral/axillary digital thermometer with LCD display and buzzer alerts.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-pillbox',
    name: '7-Day Weekly Medicine Pill Organizer',
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&q=80&w=400',
    price: 110,
    rating: 4.8,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Color-coded daily compartments (Morning, Noon, Night) to organize patient doses.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-notebook',
    name: 'Bedside Diagnosis Pocket Notebook & Pen',
    image: 'https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&q=80&w=400',
    price: 60,
    rating: 4.5,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Write down symptoms, doctor prescriptions, dietary schedules, and bills.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-tissueroll',
    name: 'Premium Double Ply Soft Toilet Tissue Roll',
    image: 'https://images.unsplash.com/photo-1584622781564-1d987f7333c1?auto=format&fit=crop&q=80&w=400',
    price: 45,
    rating: 4.7,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Soluble, ultra-soft toilet tissue roll designed for sensitive clinical use.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-mirror',
    name: 'Stand Hand Mirror (Single-Sided)',
    image: 'https://images.unsplash.com/photo-1590156221122-c241e47a2841?auto=format&fit=crop&q=80&w=400',
    price: 80,
    rating: 4.4,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Small bedside tabletop mirror for hair, hygiene, and face inspections.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },

  // Food & Healthy Snacks (20 items)
  {
    id: 'gr-water',
    name: 'Bisleri Packed Mineral Water (1L)',
    image: 'https://images.unsplash.com/photo-1608885898957-a599fb18ec3d?auto=format&fit=crop&q=80&w=400',
    price: 20,
    rating: 4.9,
    calories: 0,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Ozone treated and multi-filtered secure drinking mineral water.',
    ingredients: [],
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-coconut',
    name: 'Real Coconut Water (200ml Tetra Pack)',
    image: 'https://images.unsplash.com/photo-1543157148-f68f214fb391?auto=format&fit=crop&q=80&w=400',
    price: 50,
    rating: 4.8,
    calories: 40,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Natural electrolytes hydration booster, helps restore mineral levels instantly.',
    ingredients: [],
    nutrition: { calories: 40, protein: 0, carbs: 9, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-greentea',
    name: 'Organic Lemon Green Tea Bags (Pack of 20)',
    image: 'https://images.unsplash.com/photo-1563822249548-9a72b6353cd1?auto=format&fit=crop&q=80&w=400',
    price: 140,
    rating: 4.8,
    calories: 2,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Rich in antioxidants, aids active metabolism and clinical recovery.',
    ingredients: [],
    nutrition: { calories: 2, protein: 0, carbs: 0.5, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-digestive',
    name: 'McVities High-Fiber Digestive Biscuits',
    image: 'https://images.unsplash.com/photo-1558961309-dbdf71799f14?auto=format&fit=crop&q=80&w=400',
    price: 70,
    rating: 4.7,
    calories: 140,
    protein: 2.5,
    category: 'Grocery',
    isVeg: true,
    description: 'Made with whole wheat flour. Light, semi-sweet and healthy digestive biscuits.',
    ingredients: [],
    nutrition: { calories: 140, protein: 2.5, carbs: 22, fat: 5, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-oatcookies',
    name: 'Nutri-Choice Oats & Milk Cookies (150g)',
    image: 'https://images.unsplash.com/photo-1558961309-dbdf71799f14?auto=format&fit=crop&q=80&w=400',
    price: 80,
    rating: 4.7,
    calories: 160,
    protein: 3,
    category: 'Grocery',
    isVeg: true,
    description: 'Delicious oats-baked biscuits, loaded with complex grain fiber.',
    ingredients: [],
    nutrition: { calories: 160, protein: 3, carbs: 24, fat: 6, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-sugarfree',
    name: 'Britannia Sugar-Free Cream Crackers',
    image: 'https://images.unsplash.com/photo-1558961309-dbdf71799f14?auto=format&fit=crop&q=80&w=400',
    price: 90,
    rating: 4.6,
    calories: 110,
    protein: 2,
    category: 'Grocery',
    isVeg: true,
    description: 'Sugar-free dry biscuits, highly recommended for diabetic patients.',
    ingredients: [],
    nutrition: { calories: 110, protein: 2, carbs: 16, fat: 4, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-almonds',
    name: 'California Premium Almonds (100g)',
    image: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?auto=format&fit=crop&q=80&w=400',
    price: 180,
    rating: 4.9,
    calories: 570,
    protein: 21,
    category: 'Grocery',
    isVeg: true,
    description: 'Natural high-fiber brain food, rich in healthy fats, vitamin E, and magnesium.',
    ingredients: [],
    nutrition: { calories: 570, protein: 21, carbs: 22, fat: 49, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-walnuts',
    name: 'Premium Chilean Walnuts / Akhrot (100g)',
    image: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?auto=format&fit=crop&q=80&w=400',
    price: 240,
    rating: 4.8,
    calories: 650,
    protein: 15,
    category: 'Grocery',
    isVeg: true,
    description: 'Rich in Omega-3 fatty acids. Premium skinless walnuts.',
    ingredients: [],
    nutrition: { calories: 650, protein: 15, carbs: 14, fat: 65, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-juice',
    name: 'Paper Boat Aromatic Pomegranate Juice',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=400',
    price: 40,
    rating: 4.7,
    calories: 120,
    protein: 1,
    category: 'Grocery',
    isVeg: true,
    description: 'Enriched with antioxidants, no added preservatives or colors.',
    ingredients: [],
    nutrition: { calories: 120, protein: 1, carbs: 29, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-ors',
    name: 'WHO Hydralyte ORS Apple Hydration (200ml)',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=400',
    price: 35,
    rating: 4.9,
    calories: 30,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Scientifically formulated WHO-formula oral rehydration beverage to prevent dehydration.',
    ingredients: [],
    nutrition: { calories: 30, protein: 0, carbs: 7.5, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-apples',
    name: 'Fresh Crisp Red Apples (Set of 2)',
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&q=80&w=400',
    price: 90,
    rating: 4.8,
    calories: 104,
    protein: 0.5,
    category: 'Grocery',
    isVeg: true,
    description: 'Rich in vitamin C and dietary fibers. Freshly sanitized and cleaned.',
    ingredients: [],
    nutrition: { calories: 104, protein: 0.5, carbs: 28, fat: 0.3, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-bananas',
    name: 'Fresh Golden Robusta Bananas (Set of 3)',
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&q=80&w=400',
    price: 40,
    rating: 4.8,
    calories: 260,
    protein: 3,
    category: 'Grocery',
    isVeg: true,
    description: 'Instant recovery energy, rich in natural potassium and magnesium.',
    ingredients: [],
    nutrition: { calories: 260, protein: 3, carbs: 68, fat: 0.6, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-pomegranate',
    name: 'Bedside Peeled Fresh Pomegranate Cup',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=400',
    price: 110,
    rating: 4.9,
    calories: 130,
    protein: 2,
    category: 'Grocery',
    isVeg: true,
    description: 'Ready-to-eat peeled fresh pomegranate ruby seeds, aids hemoglobin building.',
    ingredients: [],
    nutrition: { calories: 130, protein: 2, carbs: 32, fat: 1, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-makhana',
    name: 'Roasted Low-Salt Organic Makhana (50g)',
    image: 'https://images.unsplash.com/photo-1600180758890-6b94519a8ba6?auto=format&fit=crop&q=80&w=400',
    price: 120,
    rating: 4.8,
    calories: 180,
    protein: 4.5,
    category: 'Grocery',
    isVeg: true,
    description: 'Dry-roasted healthy water lily seeds, zero trans-fats and high calcium.',
    ingredients: [],
    nutrition: { calories: 180, protein: 4.5, carbs: 34, fat: 2, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-darkchoc',
    name: 'Amul 75% Bitter Dark Chocolate (150g)',
    image: 'https://images.unsplash.com/photo-1548907040-4d42b52145ca?auto=format&fit=crop&q=80&w=400',
    price: 150,
    rating: 4.8,
    calories: 550,
    protein: 7,
    category: 'Grocery',
    isVeg: true,
    description: 'Bitter rich dark chocolate. Elevates mood and aids antioxidants recovery.',
    ingredients: [],
    nutrition: { calories: 550, protein: 7, carbs: 45, fat: 38, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-amlacandy',
    name: 'Sweet & Sour Dried Amla Candies (100g)',
    image: 'https://images.unsplash.com/photo-1600180758890-6b94519a8ba6?auto=format&fit=crop&q=80&w=400',
    price: 85,
    rating: 4.6,
    calories: 160,
    protein: 0.5,
    category: 'Grocery',
    isVeg: true,
    description: 'Sun-dried amla, extremely rich in organic vitamin C, boosts immune pathways.',
    ingredients: [],
    nutrition: { calories: 160, protein: 0.5, carbs: 39, fat: 0.1, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-gingercandy',
    name: 'Bedside Soothing Ginger Herbal Lozenges (10s)',
    image: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&q=80&w=400',
    price: 60,
    rating: 4.7,
    calories: 40,
    protein: 0,
    category: 'Grocery',
    isVeg: true,
    description: 'Soothes dry coughs, throat irritations, and chemotherapy/post-operation nausea.',
    ingredients: [],
    nutrition: { calories: 40, protein: 0, carbs: 10, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-honey',
    name: 'Organic Honey Squeeze Twister (100g)',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=400',
    price: 95,
    rating: 4.8,
    calories: 304,
    protein: 0.3,
    category: 'Grocery',
    isVeg: true,
    description: 'Pure multi-floral honey in an easy bedside squeeze tube. Great for dry coughs.',
    ingredients: [],
    nutrition: { calories: 304, protein: 0.3, carbs: 82, fat: 0, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-chana',
    name: 'Roasted Skinless Salted Chana (150g)',
    image: 'https://images.unsplash.com/photo-1600180758890-6b94519a8ba6?auto=format&fit=crop&q=80&w=400',
    price: 65,
    rating: 4.7,
    calories: 240,
    protein: 15,
    category: 'Grocery',
    isVeg: true,
    description: 'High in iron and proteins. Crunchy, easily snackable low GI bedside nuts.',
    ingredients: [],
    nutrition: { calories: 240, protein: 15, carbs: 38, fat: 4, prepTimeMinutes: 0 },
    reviews: [],
  },
  {
    id: 'gr-multipuff',
    name: 'Multi-Grain Bedside Diet Puffs (70g)',
    image: 'https://images.unsplash.com/photo-1600180758890-6b94519a8ba6?auto=format&fit=crop&q=80&w=400',
    price: 55,
    rating: 4.6,
    calories: 190,
    protein: 4,
    category: 'Grocery',
    isVeg: true,
    description: 'Roasted grain puffs made of ragi, oats, and millet. High fiber and low sodium snack.',
    ingredients: [],
    nutrition: { calories: 190, protein: 4, carbs: 42, fat: 1.5, prepTimeMinutes: 0 },
    reviews: [],
  },
];
